# Refer to uv-docker-example:
# https://github.com/astral-sh/uv-docker-example/blob/main/standalone.Dockerfile
# Note that we use uv to launch, so we omit the second half of the example (non-UV final image)

FROM nvidia/cuda:12.8.0-devel-ubuntu24.04
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libegl-dev \
    fuse3 \
    rclone \
    htop \
    tmux \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1
ENV UV_PYTHON_PREFERENCE=only-managed    
ENV MUJOCO_GL=egl
ENV UV_PYTHON_INSTALL_DIR=/app/.python
ENV UV_CACHE_DIR=/app/.cache/uv
ENV WARP_CACHE_PATH=/app/.cache/warp
ENV WANDB_DIR=/app/wandb_logs \
    WANDB_CACHE_DIR=/app/.cache/wandb \
    WANDB_ARTIFACT_DIR=/app/artifacts \
    WANDB_DATA_DIR=/app/.wandb_data \
    WANDB_CONSOLE=off



RUN uv python install 3.13

WORKDIR /app

RUN mkdir -p .cache/uv .cache/warp .cache/wandb

RUN --mount=type=cache,target=/app/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-editable --no-dev

RUN --mount=type=cache,target=/app/.cache/uv \
    uv pip install vastai wandb gdown uv-build hatchling

ADD . /app


RUN git config --global --add safe.directory /app && \
    git remote set-url origin https://github.com/HaizhouZ/mjlab2.git

RUN --mount=type=cache,target=/app/.cache/uv \
    uv sync --frozen --no-editable --no-dev --no-build-isolation

EXPOSE 8080

# startup script
COPY vastai_entrypoint.sh /vastai_entrypoint.sh
RUN chmod +x /vastai_entrypoint.sh
ENTRYPOINT ["/vastai_entrypoint.sh"]