agent:
  experiment_name: g1_velocity_reppo
  save_interval: 50
  num_steps_per_env: 24
  max_iterations: 30000
  policy:
    class_name: ActorQ
    init_noise_std: 1.0
    actor_obs_normalization: true
    critic_obs_normalization: true
    actor_hidden_dims: [512, 256, 128]
    critic_hidden_dims: [512, 256, 128]
    activation: elu
    distribution_type: tanh
    init_alpha_temp: 0.001
    init_alpha_kl: 0.01
    num_critic_bins: 151
    vmin: -20.0
    vmax: 15.0
  algorithm:
    class_name: REPPO
    learning_rate: 3.0e-4
    gamma: 0.99
    lam: 0.95
    max_grad_norm: 0.5
    num_learning_epochs: 4
    num_mini_batches: 32
    desired_kl: 0.1
    target_entropy: -0.5
