agent:
  experiment_name: g1_velocity_reppo
  save_interval: 50
  num_steps_per_env: 24
  max_iterations: 30000
  policy:
    class_name: ReppoPolicy
    critic_class_name: ReppoCritic
    init_noise_std: 1.0
    actor_min_std: 0.1
    ent_start: 0.001
    kl_start: 0.01
    actor_obs_normalization: true
    critic_obs_normalization: true
    actor_hidden_dims: [512, 256, 128]
    critic_hidden_dims: [512, 256, 128]
    activation: elu
  algorithm:
    class_name: Reppo
    learning_rate: 3.0e-4
    schedule: fixed
    gamma: 0.99
    lam: 0.95
    max_grad_norm: 0.5
    num_learning_epochs: 4
    num_mini_batches: 32
    num_atoms: 151
    vmin: -20.0
    vmax: 15.0
    aux_loss_mult: 0.0
    kl_bound: 0.1
    actor_kl_clip_mode: full
    ent_target_mult: 0.5
    num_action_samples: 64
